alias d='dirs -v'
alias h='history'

alias rm='rm -vf'
alias rmr='rm -R'
alias cp='cp -Ri'
alias mv='mv -i'

alias ls='ls --color=auto -F'
alias l='ls'
alias ll='ls -l'
alias lss='ls -sh'
alias lsa='ls -A'
alias lsd='ls -d'
alias lld='ls -ld'
alias lla='ls -lA'

alias cd..='cd ..'
alias ..='cd ..'
alias ...='cd ../../'
alias ....='cd ../../../'
